[package]
name = "twine_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
twine_core = { path = "../twine_core" }
twine_builder = { path = "../twine_builder" }
twine_http_store = { path = "../twine_http_store" }
twine_sled_store = { path = "../twine_sled_store" }
futures = "0.3"
serde = { version = "1.0" }
itertools = "0.12"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
confy = "0.6"
clap = { version = "4", features = ["derive"] }
directories = "5.0"
anyhow = "1.0"
indicatif = "0.17"
log = "0.4"
simple_logger = { version = "5", features = ["colors"], default-features = false}
