[package]
name = "twine_core"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libipld = "0.16.0"
serde = "1.0.152"
josekit = "0.8.2"