[package]
name = "twine_core"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libipld = { version="0.16.0", features=["serde-codec"] }
serde = "1.0.152"
josekit = "0.8.2"
serde_ipld_dagcbor = "0.3.0"
thiserror = "1.0.40"
base64 = "0.21.0"

[dev-dependencies]
twine_builder = { path = "../twine_builder" }
serde_json = "1.0"
