[package]
name = "twine"
version = "0.0.1"
authors = ["Twine protocol developers"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/twine-protocol/twine-rs"
documentation = ""
homepage = ""
description = """
Twine prococol library
"""
keywords = ["twine"]
categories = []
edition = "2021"

[workspace]
members = [
  "./twine_core",
  "./twine_builder",
  "./twine_http_store",
  "./twine_sled_store",
]

[dependencies]
twine_core = { path = "./twine_core" }

[dev-dependencies]
