[package]
name = "twine_builder"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twine_core = { path = "../twine_core" }
libipld = "0.16.0"
serde = "1.0.152"
josekit = "0.8.2"
serde_ipld_dagcbor = "0.3.0"
thiserror = "1.0.40"
linked-hash-map = "0.5.6"

[dev-dependencies]
serde_json = "1.0"