[package]
name = "twine_builder"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twine_core = { path = "../twine_core/" }
thiserror = "1.0.40"
futures = "0.3"
josekit = "0.8"
anyhow = "1.0"

[dev-dependencies]
serde_json = "1.0"