[package]
name = "test_apis"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twine_builder = { path = "../twine_builder" }
twine_core = { path = "../twine_core" }
rocket = "0.5.0-rc.3"