[package]
name = "twine_http_store"
version = "0.0.1"
edition = "2021"
rust-version = "1.78"

[dependencies]
twine_core = { path = "../twine_core" }
reqwest = { version = "0.12", features = ["stream", "brotli", "json"] }
futures = "0.3"
async-trait = "0.1"
# fvm_ipld_car = "0.7"
serde = { version = "1.0" }
itertools = "0.13"
serde_json = "1.0"
backon = "1.3"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
futures-time = "3.0"
