name: CI

on:
  push:
    branches:
      - $default-branch
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, wasm32-unknown-unknown]
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: swatinem/rust-cache@v2

      - name: Install WASM Test Dependencies
        if: matrix.target == 'wasm32-unknown-unknown'
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli

      - name: Run Tests (Native)
        if: matrix.target != 'wasm32-unknown-unknown'
        run: cargo test --workspace --target ${{ matrix.target }}

      - name: Run Tests (WASM)
        if: matrix.target == 'wasm32-unknown-unknown'
        run: |
          cargo test --workspace --target wasm32-unknown-unknown