name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests for ${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: wasm32-unknown-unknown
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable

      - name: Install wasm32 target
        if: matrix.target == 'wasm32-unknown-unknown'
        run: rustup target add wasm32-unknown-unknown

      - name: Install cross-compilation tools
        if: matrix.target != 'wasm32-unknown-unknown'
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: Cache dependencies
        uses: swatinem/rust-cache@v2

      - name: Check (WASM)
        if: matrix.target == 'wasm32-unknown-unknown'
        run: cargo check --package twine_lib --package twine_builder --package twine_http_store --target wasm32-unknown-unknown

      - name: Run Tests
        if: matrix.target != 'wasm32-unknown-unknown'
        run: cargo test --workspace --target ${{ matrix.target }}
