name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [x86_64-unknown-linux-gnu, aarch64-apple-darwin, aarch64-unknown-linux-gnu, x86_64-pc-windows-gnu, wasm32-unknown-unknown]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: Cache dependencies
        uses: swatinem/rust-cache@v2

      - name: Check (WASM)
        if: matrix.target == 'wasm32-unknown-unknown'
        run: cargo check --package twine_core --package twine_builder --package twine_http_store --target wasm32-unknown-unknown

      - name: Run Tests
        if: matrix.target != 'wasm32-unknown-unknown'
        run: cargo test --workspace --target ${{ matrix.target }}
