name: Release please

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]


jobs:
  release:
    name: Release Please
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.release.outputs.releases_created }}
      # json array of paths to the released packages
      paths: ${{ steps.release.outputs.paths_released }}
    steps:
      - name: Run Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: rust
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to crates.io
    needs: release
    if: needs.release.outputs.created
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: ${{ fromJSON(needs.release.outputs.paths) }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish ${{ matrix.item }}
        run: >
          cargo publish
          --package ${{ matrix.item }}
          --verbose
          --locked
          --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
